const fs=require('node:fs'),assert=require('node:assert/strict');
const js=fs.readFileSync('console.js','utf8'),css=fs.readFileSync('ui-refresh.css','utf8');
const section=(a,b)=>js.slice(js.indexOf(a),js.indexOf(b));
const upload=section('function uploadModal(','function libraryPickerModal(');
assert(!upload.includes('new-group-from-upload'));
assert(upload.includes('暂无分组，请先到图片资源页面新建'));
assert(upload.includes('new DataTransfer()')&&upload.includes("zone.addEventListener('drop'"));
const settings=section('function settingsPage()','async function loadAdminPolicy()');
assert(!settings.includes('<h2>仓库设置</h2>'));
assert(!settings.includes('网站不会要求你复制或粘贴 GitHub Token'));
for(const action of ['create-repo','rename-repo','delete-repo','logout','open-repo'])assert(settings.includes(`data-action="${action}"`));
assert(settings.includes('Token 只在服务器内存会话中使用'));
assert(!section('function adminPage()','function renderC()').includes('<h2>管理后台</h2>'));
assert(css.includes('.settings-card{box-shadow:none}'));
assert(css.includes('.modal :is(.btn,.modal-close,.field-menu-trigger),.settings-card .btn{min-height:44px}'));
assert(!css.includes('modal-inline-create'));
const html=fs.readFileSync('index.html','utf8');
for(const file of ['console.js','ui-refresh.css'])assert(html.includes(file+'?v=https-initial-caption-103&amp;revision=clean-ui-release-123'),file+' release cache revision');
console.log('PASS clean-site: duplicate removal, no-group and upload flow, settings actions/identity/security, scoped 44px modal targets');
