const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const github=fs.readFileSync('github.js','utf8'),ui=fs.readFileSync('console.js','utf8');
const GitHubClient=vm.runInNewContext(github+';GitHubClient',{window:{},TextDecoder,Uint8Array,atob,btoa,URL,structuredClone});
const clone=x=>structuredClone(x),blob=(path,sha='sha-'+path,mode='100644')=>({path,sha,mode,type:'blob'});
const config={owner:'User',repo:'Repo name',branch:'feature/a 中文',assetsPath:'assets'};
function fixture(){const c=new GitHubClient(config);const a=blob('assets/one/A space.PNG'),b=blob('assets/two/b.svg');const raw=c.raw(a.path);return {head:'head0',tree:'tree0',directories:['assets','assets/one','assets/two','assets/empty','assets/dest'],entries:[a,b,blob('assets/empty/.gitkeep')],docs:[{path:'json/z.json',sha:'z',value:{name:'z',extra:7,icons:[{name:'custom B',url:c.raw(b.path),tag:9},{name:'custom A',url:raw},{name:'duplicate',url:raw+'?v=1#x'},{name:'external',url:raw.replace('feature%2Fa%20%E4%B8%AD%E6%96%87','main')}] }},{path:'other/library.json',sha:'o',value:{icons:[{name:'encoded',url:raw.replace('A%20space','A space')},{name:'foreign',url:'https://example.com/a.png'}]}},{path:'plain.json',sha:'p',value:{icons:[]}}]};}
function harness(snap=fixture()){
 const c=new GitHubClient(config),calls=[];let snapshots=[clone(snap)],at=0;
 c.snapshot=async()=>clone(snapshots[Math.min(at++,snapshots.length-1)]);
 c.request=async(path,method='GET',body)=>{calls.push({path,method,body:clone(body)});if(path.endsWith('/git/trees'))return {sha:'newtree'};if(path.endsWith('/git/commits'))return {sha:'newcommit'};if(method==='PATCH')return {};throw new Error('Unexpected request '+path);};
 return {c,calls,snap,setSnapshots:values=>{snapshots=values;at=0;}};
}
function tree(h){return h.calls.find(x=>x.path.endsWith('/git/trees'))?.body.tree;}
let cases=0;async function test(name,run){await run();cases++;console.log('PASS move-groups '+name);}
(async()=>{
 await test('single blob reuse; source basename case and custom icon name preserved',async()=>{const h=harness(),a=h.snap.entries[0],r=await h.c.moveSelected([a],'dest');assert.equal(r.moved,1);assert.equal(r.skipped,0);assert.equal(h.calls.length,3);const t=tree(h);assert.equal(t[0].sha,null);assert.equal(t[1].sha,a.sha);assert.equal(t[1].path,'assets/dest/A space.PNG');assert(!h.calls.some(x=>x.path.includes('/blobs')));const doc=JSON.parse(t.find(x=>x.path==='json/z.json').content);assert.equal(doc.extra,7);assert.deepEqual(doc.icons.map(i=>i.name),['custom B','custom A','duplicate','external']);assert.equal(doc.icons[1].url,h.c.raw(t[1].path));assert.equal(doc.icons[2].url,doc.icons[1].url);assert.equal(doc.icons[3].url,h.snap.docs[0].value.icons[3].url);assert.equal(doc.icons[0].tag,9);assert.equal(t.filter(x=>x.content).length,2);assert.equal(h.snap.docs[0].value.icons[1].url,h.c.raw(a.path));});
 await test('batch one tree one commit one nonforce branch update; reverse source order',async()=>{const h=harness(),r=await h.c.moveSelected(h.snap.entries.slice(0,2).reverse(),'dest');assert.equal(r.moved,2);assert.equal(h.calls.length,3);assert.equal(h.calls[0].body.base_tree,'tree0');assert.deepEqual(h.calls[1].body.parents,['head0']);assert.equal(h.calls[2].body.force,false);assert(h.calls[2].path.endsWith(encodeURIComponent(config.branch)));assert.equal(JSON.parse(tree(h).find(x=>x.path==='json/z.json').content).icons[0].name,'custom B');});
 await test('same group skipped; mixed skip plus move; no-op has zero writes',async()=>{const h=harness(),r=await h.c.moveSelected(h.snap.entries.slice(0,2),'one');assert.equal(r.moved,1);assert.equal(r.skipped,1);const z=harness(),n=await z.c.moveSelected([z.snap.entries[0]],'one');assert.equal(n.changed,false);assert.equal(n.skipped,1);assert.equal(z.calls.length,0);});
 await test('existing empty group accepted',async()=>{const h=harness();assert.equal((await h.c.moveSelected([h.snap.entries[0]],'empty')).moved,1);});
 await test('invalid targets sources and no group rejected without writes',async()=>{for(const group of ['', '../dest','/dest','dest/child','dest\\x','dest\u0000','new']){const h=harness();await assert.rejects(()=>h.c.moveSelected([h.snap.entries[0]],group));assert.equal(h.calls.length,0);}for(const path of ['README.png','json/a.png','assets/../a.png','assets//a.png','assets/a.txt','assets/one/../a.png']){const h=harness();await assert.rejects(()=>h.c.moveSelected([blob(path)],'dest'));assert.equal(h.calls.length,0);}const h=harness();await assert.rejects(()=>h.c.moveSelected([],'dest'));assert.equal(h.calls.length,0);});
 await test('duplicate basename across sources blocks entire batch',async()=>{const h=harness();const a=blob('assets/two/A space.PNG');h.snap.entries.push(a);h.setSnapshots([h.snap]);await assert.rejects(()=>h.c.moveSelected([h.snap.entries[0],a],'dest'),/同名/);assert.equal(h.calls.length,0);});
 await test('target files same sha; selected target self; directory and duplicate selection conflicts',async()=>{for(const self of [false,true]){const h=harness(),a=h.snap.entries[0],b=blob('assets/dest/A space.PNG',a.sha);h.snap.entries.push(b);h.setSnapshots([h.snap]);await assert.rejects(()=>h.c.moveSelected(self?[b,a]:[a],'dest'),/同名/);assert.equal(h.calls.length,0);}const h=harness();h.snap.directories.push('assets/dest/A space.PNG');h.setSnapshots([h.snap]);await assert.rejects(()=>h.c.moveSelected([h.snap.entries[0]],'dest'),/同名/);assert.equal(h.calls.length,0);await assert.rejects(()=>h.c.moveSelected([h.snap.entries[0],h.snap.entries[0]],'dest'),/重复/);});
 await test('stale blob missing file and symlink blocked before writes',async()=>{for(const change of ['changed','missing','symlink']){const h=harness(),a=clone(h.snap.entries[0]);if(change==='missing')h.snap.entries.shift();else if(change==='changed')h.snap.entries[0].sha='newsha';else h.snap.entries[0].mode='120000';h.setSnapshots([h.snap]);await assert.rejects(()=>h.c.moveSelected([a],'dest'),/变化或不存在/);assert.equal(h.calls.length,0);}});
 await test('optimistic retry rebuilds latest JSON but never adopts changed source',async()=>{for(const stale of [false,true]){const h=harness(),a=h.snap.entries[0],latest=clone(h.snap);latest.head='head1';latest.tree='tree1';latest.docs[0].value.icons.reverse();if(stale)latest.entries[0].sha='edited';h.setSnapshots([h.snap,latest]);let patches=0;const request=h.c.request;h.c.request=async(path,method,body)=>{if(method==='PATCH'&&patches++===0){h.calls.push({path,method,body});throw Object.assign(new Error('conflict'),{status:409});}if(path.includes('/git/ref/'))return {object:{sha:'head1'}};if(path.includes('/compare/'))return {status:'diverged'};return request(path,method,body);};if(stale){await assert.rejects(()=>h.c.moveSelected([a],'dest'),/变化/);assert.equal(h.calls.filter(x=>x.method==='PATCH').length,1);}else{const r=await h.c.moveSelected([a],'dest');assert.equal(r.moved,1);const trees=h.calls.filter(x=>x.path.endsWith('/git/trees'));assert.equal(trees.length,2);assert.equal(trees[1].body.base_tree,'tree1');assert.deepEqual(JSON.parse(trees[1].body.tree.find(x=>x.path==='json/z.json').content).icons.map(i=>i.name),latest.docs[0].value.icons.map(i=>i.name));}}});
 await test('failed preflight retry works; empty snapshot never initializes',async()=>{const h=harness(),a=h.snap.entries[0];h.snap.entries.push(blob('assets/dest/A space.PNG'));h.setSnapshots([h.snap]);await assert.rejects(()=>h.c.moveSelected([a],'dest'));h.snap.entries.pop();h.setSnapshots([h.snap]);assert.equal((await h.c.moveSelected([a],'dest')).moved,1);const z=harness();z.c.snapshot=async()=>{throw Object.assign(new Error('empty'),{status:404});};await assert.rejects(()=>z.c.moveSelected([a],'dest'),/empty/);assert.equal(z.calls.length,0);});
 await test('actual snapshot tracks every icons library and excludes unrelated JSON',async()=>{const c=new GitHubClient(config),values={'a':{icons:[{name:'x',url:c.raw('assets/one/x.png')}]},b:{unrelated:true},d:{icons:[{name:'dup',url:c.raw('assets/one/x.png')}]}};c.request=async path=>path.includes('/git/ref/')?{object:{sha:'head'}}:path.includes('/git/commits/')?{tree:{sha:'tree'}}:path.includes('/git/trees/')?{tree:[blob('assets/one/x.png','img'),blob('json/a.json','a'),blob('other.json','b'),blob('elsewhere/d.json','d')]}:{content:btoa(JSON.stringify(values[path.split('/').at(-1)]))};assert.deepEqual(Array.from((await c.snapshot()).docs,d=>d.path),['json/a.json','elsewhere/d.json']);});
 const moveCode=ui.slice(ui.indexOf('// Begin image-group move UI'),ui.indexOf('// End image-group move UI'));
 function uiHarness(){const notices=[],S={auth:{login:'u'},connected:true,groups:[{name:'one'},{name:'dest'}],assets:[{id:'assets/one/a.png',path:'assets/one/a.png',sha:'a',group:'one'}],selected:new Set(['assets/one/a.png'])};let html='',renders=0,closes=0,refreshes=0,form;const client={moveSelected:async()=>({changed:true,moved:1,skipped:0})};const ctx={S,notify:(...a)=>notices.push(a),currentClient:()=>client,openC:h=>{html=h;form={elements:{moveGroup:{value:'dest',addEventListener(){}}},querySelector:s=>s.includes('trigger')?{setAttribute(){}}:{textContent:''}};},$c:()=>form,fieldMenuC:()=>'',FormData:class {constructor(f){this.f=f}get(){return this.f.elements.moveGroup.value}},closeC:()=>{closes++},renderC:()=>{renders++},refreshCommittedC:async()=>{refreshes++},Set};vm.runInNewContext(moveCode+';globalThis.fn={moveModal,submitMoveC}',ctx);return {ctx,S,client,notices,get html(){return html},get form(){return form},get closes(){return closes},get refreshes(){return refreshes}};}
 await test('modal count warnings same flow permission and no-group UI',async()=>{const h=uiHarness();h.ctx.fn.moveModal();assert(h.html.includes('已选择 1 张图片'));assert(h.html.includes('外部使用旧直链'));assert(!h.html.includes('不可恢复'));assert.equal(h.form.moveItems.length,1);h.S.auth=null;h.ctx.fn.moveModal();assert.equal(h.notices.at(-1)[0],'请先登录并连接仓库');h.S.auth={};h.S.groups=[];h.ctx.fn.moveModal();assert(h.html.includes('暂无可用分组'));assert(h.html.includes('disabled'));});
 await test('failure keeps selection and draft; retry clears and refreshes once',async()=>{const h=uiHarness();h.ctx.fn.moveModal();h.client.moveSelected=async()=>{throw new Error('target conflict')};await assert.rejects(()=>h.ctx.fn.submitMoveC(h.form),/conflict/);assert.equal(h.closes,0);assert.equal(h.S.selected.size,1);assert.equal(h.form.elements.moveGroup.value,'dest');h.client.moveSelected=async()=>({changed:true,moved:1,skipped:0});await h.ctx.fn.submitMoveC(h.form);assert.equal(h.S.selected.size,0);assert.equal(h.closes,1);assert.equal(h.refreshes,1);assert(h.notices.at(-1)[0].includes('已移动 1 张'));});
 await test('single entry preserves other selections; unknown outcomes block retry; submit guard',async()=>{const h=uiHarness();h.S.assets.push({id:'other'});h.S.selected.add('other');h.ctx.fn.moveModal(h.S.assets[0]);await h.ctx.fn.submitMoveC(h.form);assert(h.S.selected.has('other'));const z=uiHarness();z.ctx.fn.moveModal();let writes=0;z.client.moveSelected=async()=>{writes++;throw Object.assign(new Error('unknown'),{code:'COMMIT_OUTCOME_UNKNOWN'})};await assert.rejects(()=>z.ctx.fn.submitMoveC(z.form));await assert.rejects(()=>z.ctx.fn.submitMoveC(z.form),/不要直接重试/);assert.equal(writes,1);z.S.connected=false;await assert.rejects(()=>z.ctx.fn.submitMoveC(z.form),/连接已变化/);});
 await test('UI integration narrow: no JSON move, selection stable, copy IME locks unchanged',async()=>{assert.equal((ui.match(/data-action="bulk-move"/g)||[]).length,2);assert(ui.includes("if(form.id==='moveForm') return await submitMoveC(form)"));assert(ui.includes("if(pendingSubmission){e.preventDefault();return;}"));const icons=ui.slice(ui.indexOf('function iconModal('),ui.indexOf('// Begin image-group move UI'));assert(!icons.includes('move-asset'));const libraries=ui.slice(ui.indexOf('function librariesView('),ui.indexOf('function assetView('));assert(!libraries.includes('bulk-move'));assert(ui.includes('syncAssetSelectionUI([id])'));});
 console.log(`PASS move-groups: ${cases} feature cases (mock only, no network)`);
})().catch(e=>{console.error(e);process.exitCode=1});
