const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
const source=fs.readFileSync('server.mjs','utf8').replace(/^import .*;\n/gm,'').replace('import.meta.url',JSON.stringify('file:///fixture/server.mjs'));
async function boot(env={},mode='success'){
 let handler,calls=0;const context={URL,URLSearchParams,Buffer,AbortSignal,console:{log(){}},process:{env:{PUBLIC_BASE_URL:'https://img.beiwang02.cn',GITHUB_CLIENT_ID:'fixture-id',GITHUB_CLIENT_SECRET:'fixture-secret',...env}},dirname:path.dirname,readFile:async()=>{throw Object.assign(Error(),{code:'ENOENT'})},randomBytes:crypto.randomBytes,timingSafeEqual:crypto.timingSafeEqual,setInterval:()=>({unref(){}}),http:{createServer:fn=>{handler=fn;return{listen(){}}}},fetch:async(url,opts)=>{calls++;if(mode==='network')throw Error('fixture network');if(url.includes('access_token'))return {ok:mode!=='exchange',json:async()=>mode==='exchange'?{}:{access_token:'fixture-only-oauth-token'}};assert.equal(opts.headers.Authorization,'Bearer fixture-only-oauth-token');return {ok:mode!=='user',json:async()=>({login:'member'})}}};vm.createContext(context);const api=await vm.runInContext('(async()=>{'+source+';return {sessions,oauthStates};})()',context);
 const request=async(route,cookie='')=>{let status,data,headers={};await handler({url:route,method:'GET',headers:{cookie}},{headersSent:false,setHeader(k,v){headers[k]=v},writeHead(s,h){status=s;Object.assign(headers,h);this.headersSent=true},end(v){data=v}});return {status,headers,data}};
 const start=async()=>{const r=await request('/api/auth/github');assert.equal(r.status,302);const u=new URL(r.headers.Location);assert.equal(u.origin,'https://github.com');assert.equal(u.searchParams.get('scope'),'public_repo');assert.equal(u.searchParams.get('redirect_uri'),'https://img.beiwang02.cn/api/auth/github/callback');assert(r.headers['Set-Cookie'].includes('Secure'));assert(r.headers['Set-Cookie'].includes('HttpOnly'));return {state:u.searchParams.get('state'),cookie:r.headers['Set-Cookie'].split(';')[0]}};
 return {...api,request,start,get calls(){return calls}};
}
(async()=>{
 const disabled=await boot({GITHUB_CLIENT_ID:'',GITHUB_CLIENT_SECRET:''});assert.equal(JSON.parse((await disabled.request('/api/auth/me')).data).oauthEnabled,false);assert.equal(disabled.calls,0);assert((await disabled.request('/api/auth/github')).headers.Location.includes('oauth_not_configured'));
 await assert.rejects(boot({GITHUB_OAUTH_REDIRECT_URI:'https://evil.test/api/auth/github/callback'}),/同源/);
 const b=await boot();assert(JSON.parse((await b.request('/api/auth/me')).data).oauthEnabled);
 for(const kind of ['missing','mismatch','expired','cancel','code']){const t=await b.start();if(kind==='expired')b.oauthStates.get(t.state).expires=0;const r=await b.request('/api/auth/github/callback?state='+t.state+(kind==='cancel'?'&error=access_denied':kind==='code'?'':'&code=fixture'),kind==='missing'?'':kind==='mismatch'?'gh_oauth_state=wrong':t.cookie);assert.equal(r.status,302);assert.equal(new URL(r.headers.Location).origin,'https://img.beiwang02.cn');assert(r.headers.Location.includes(kind==='cancel'?'oauth_denied':kind==='code'?'oauth_code':'oauth_state'));}assert.equal(b.calls,0);
 const t=await b.start(),r=await b.request('/api/auth/github/callback?state='+t.state+'&code=fixture',t.cookie);assert.equal(r.headers.Location,'https://img.beiwang02.cn/');assert.equal(b.sessions.size,1);assert.equal([...b.sessions.values()][0].token,'fixture-only-oauth-token');assert(r.headers['Set-Cookie'][1].includes('Secure'));assert(!JSON.stringify(r).includes('fixture-only-oauth-token'));assert((await b.request('/api/auth/github/callback?state='+t.state+'&code=fixture',t.cookie)).headers.Location.includes('oauth_state'));
 for(const mode of ['network','exchange','user']){const b=await boot({},mode),t=await b.start(),r=await b.request('/api/auth/github/callback?state='+t.state+'&code=fixture',t.cookie);assert.equal(r.status,302);assert(r.headers.Location.includes('auth_error='));assert.equal(b.sessions.size,0)}
 const f=await boot({ALLOWED_GITHUB_LOGINS:'other'}),ft=await f.start();assert((await f.request('/api/auth/github/callback?state='+ft.state+'&code=fixture',ft.cookie)).headers.Location.includes('forbidden'));assert.equal(f.sessions.size,0);
 console.log('PASS OAuth mock endpoints: disabled/enabled, same-origin callback, secure HttpOnly cookies, missing/mismatch/expired/replay state, cancellation/missing code, exchange/network/user errors, whitelist, memory-only session and direct API token');
})().catch(e=>{console.error(e);process.exitCode=1});
